# action.yml
name: 'Autorest Legacy'
description: 'Autorest legacy environment'
inputs:
  input-file:
    description: 'The file path or URL of swagger file'
    required: true
  clear-output-folder:
    description: 'clear the output folder before code generation; default: false'
    default: false
  override-client-name:
    description: 'Name to use for the generated client type; default: <Normalized title in swagger file>'
    default: 'ApiClient'
  namespace:
    description: 'The base namespace for generated C# code; default: Swagger'
    default: 'AutoRest'
  csharp:
    description: 'Generate C# code; default: false'
    default: false
  typescript:
    description: 'Generate TypeScript code; default: false'
    default: false
  python:
    description: 'Generate python code; default: false'
    default: false 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.input-file }}
  - ${{ inputs.clear-output-folder }}
  - ${{ inputs.override-client-name }}
  - ${{ inputs.namespace }}
  - ${{ inputs.csharp }}
  - ${{ inputs.typescript }}
  - ${{ inputs.python }}
